name = "QUBOTools"
uuid = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>", "AndradeTiago <tiago.andrade@psr-inc.com>", "joaquimg <joaquim@psr-inc.com>", "bernalde <dbernaln@purdue.edu>"]
version = "0.10.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PseudoBooleanOptimization = "c8fa9a04-bc42-452d-8558-dc51757be744"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extensions]
QUBOTools_MOI = ["MathOptInterface"]

[compat]
GeometryBasics = "0.4"
Graphs = "1"
HDF5 = "0.16.15"
JSON = "0.21.3"
JSONSchema = "1"
MathOptInterface = "1"
NetworkLayout = "0.4.5"
PseudoBooleanOptimization = "0.1"
RecipesBase = "1"
Statistics = "1"
julia = "1.9"
